# Generated by Django 6.0.4 on 2026-05-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='request_type',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='destination_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_category',
            field=models.CharField(choices=[('deplacement', 'Déplacement'), ('nettoyage', 'Nettoyage'), ('desinsectisation', 'Désinsectisation'), ('maintenance', 'Maintenance')], default='maintenance', max_length=50),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='request_subcategory',
            field=models.CharField(choices=[('materiel_informatique', 'Matériel informatique'), ('mobilier', 'Mobilier'), ('archives', 'Archives'), ('autre_deplacement', 'Autre'), ('vider_corbeille', 'Vider corbeille'), ('poussiere', 'Poussière'), ('probleme_sanitaire', 'Problème sanitaire'), ('autre_nettoyage', 'Autre'), ('fourmis', 'Fourmis'), ('cafards', 'Cafards'), ('mouches', 'Mouches'), ('moustiques', 'Moustiques'), ('rongeurs', 'Rongeurs'), ('autre_desinsectisation', 'Autre'), ('prise_electrique', 'Prise électrique'), ('led', 'LED'), ('climatiseur', 'Climatiseur'), ('autre_maintenance', 'Autre')], default='autre_maintenance', max_length=50),
        ),
    ]
